languageCode: "en-us"
baseURL: "https://engineeringangel.com/"
title: "EngineeringAngel Bulbuk"
logo: "/images/favicon.png"
theme: "anubis"
paginate: 10
disqusShortname: "EngineeringAngel"
googleAnalytics: "G-12345"
enableRobotsTXT: true

menu:
  main:
    - identifier: about
      name: About
      title: about
      url: /about/
      weight: 200

    - identifier: blog
      name: Blog
      title: blog
      url: /posts/
      weight: 100

params:
  author: "Ole Bulbuk "
  email: ole@bulbuk.de # used for microformats
  avatar: "/images/favicon.png" # used for microformats
  description: ""
  footer:
    - title: About
      content: "Delivering the best service"
    - title: Recent Blog Posts
      recents: blog
      recentCount: 7
    - title: Contact Me
      contact: true
  # Uncomment if you need this
  # images:
  #   - images/og-featured.png # relative path to "static" directory
  # customCSS:
  #   - css/my.css # relative path to "assets" directory (don't use main.css filename)
  # customJS:
  #   - js/main.js # relative path to "assets" directory
  dateFormat: "2006-01-02"
  paginationSinglePost: true
  style: light-with-switcher
  readMore: false # show read more button
  readNextPosts: 5  # show 5 related posts, 0 by default
  disableSummary: false
  copyCodeButton: true # true by default
  rssAsSocialIcon: true
  # utteranc.es support
  utterancesRepo: ""  # mandatory
  utterancesTheme: "" # optional
  utterancesIssue: "" # optional
  utterancesLabel: "" # optional
  # isso support
  isso:
    enabled: true # mandatory
    data: "https://comments.example.com/" # mandatory
    jsLocation: "https://comments.example.com/js/embed.min.js" # mandatory
    css: true # optional
    lang: "de" # optional
    replyToSelf: true # mandatory
    requireAuthor: true # mandatory
    requireEmail: true # mandatory
    id: "thread-id" # optional
    avatar: true # optional
    avatar-bg: "#f0f0f0" # optional
    feed: false # optional
  graphcommentId: ""
  webmentions:
    url: https://engineeringangel.com/
    login: hugo-theme-anubis
    pingback: true
  social:
    - id: github
      name: ole108
    - id: linkedin
      name: ole-bulbuk-96794170
#  - id: hugo
#    url: "https://github.com/ole108"
#    icon: "hugo"

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown